Initial implementation
projectsyn/component-prometheus-pushgateway pull request #1
Opened 2021-01-05 14:20 UTC by simu

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [ ] Update the ./CHANGELOG.md.
- [ ] Link this PR to related issues.

2021-01-05 14:29 UTC, simu commented on class/defaults.yml
> +      prometheus: main
Maybe we should default to `prometheus: platform` which has been the prometheus name until now.

2021-01-05 14:33 UTC, srueg requested changes

2021-01-05 14:33 UTC, srueg commented on component/main.jsonnet
> +                runbook_url: 'https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletdown',
Wrong link?

2021-01-05 14:33 UTC, srueg commented on class/prometheus-pushgateway.yml
> +        helm_values:
It might make sense to expose the full `helm_values` in the `defaults.config` to be able to configure it further via the hierarchy?

2021-01-05 14:33 UTC, srueg commented on class/defaults.yml
> +    prometheus_namespace: prometheus
Usually the `PrometheusRule` CRs should be deployed in the same namespace as the actual app, so maybe default to `${prometheus_pushgateway:namespace}`?

2021-01-06 08:02 UTC, corvus-ch approved these changes

2021-01-06 08:08 UTC, srueg approved these changes

2021-01-06 12:20 UTC, merged